// Assets/Editor/WwiseEventIdCodegen.cs
#if UNITY_EDITOR
using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEditor.VersionControl;

public static class WwiseEventIdCodegen
{
    private const string OutputDir  = "Assets/Generated/";
    private const string OutputPath = OutputDir + "/AudioEventIDs.generated.cs";

    [MenuItem("Tools/Wwise/Generate Event ID Map")]
    public static void Generate()
    {
        try
        {
            if (!AkWaapiUtilities.IsConnected())
            {
                EditorUtility.DisplayDialog(
                    "Wwise WAAPI",
                    "Not connected to Wwise Authoring.\nOpen Wwise and enable WAAPI (Preferences → WAAPI).",
                    "OK"
                );
                return;
            }

            // Ask WAAPI for fields Wwise actually returns for Events
            var options = new ReturnOptions(new[] { "name", "id", "shortId" });

            // WAQL query: all Events
            var args = new WaqlArgs("from type Event");

            AkWaapiUtilities.GetResultListDelegate<WwiseEventInfo> onComplete = results =>
            {
                if (results == null || results.Count == 0)
                {
                    Debug.LogWarning("No Wwise Events found.");
                    return;
                }

                // WAAPI does not provide a path for Events; fill a readable comment
                foreach (var e in results)
                    if (string.IsNullOrEmpty(e.path)) e.path = e.name;

                Directory.CreateDirectory(OutputDir);
                File.WriteAllText(OutputPath, BuildSource(results));
                AssetDatabase.Refresh();
                Debug.Log($"Generated Wwise Event map: {OutputPath} ({results.Count} events)");
            };

            // Your helper takes exactly (args, options, callback)
            AkWaapiUtilities.QueueCommandWithReturnWwiseObjects<WwiseEventInfo>(
                args,
                options,
                onComplete
            );
        }
        catch (Exception e)
        {
            Debug.LogError($"WwiseEventIdCodegen failed: {e}");
        }
    }

    [Serializable]
    public class WwiseEventInfo
    {
        public string name;    // Event name
        public string id;      // GUID
        public uint   shortId; // 32-bit AkUniqueID
        public string path;    // Comment only; WAAPI won't fill for Events
    }

    private static string BuildSource(List<WwiseEventInfo> events)
    {
        // Stable ordering
        events.Sort((a, b) => string.Compare(a.name, b.name, StringComparison.Ordinal));

        var usedIdentifiers = new HashSet<string>();
        var nameCounts = new Dictionary<string, int>();
        foreach (var e in events)
        {
            nameCounts[e.name] = nameCounts.TryGetValue(e.name, out var c) ? c + 1 : 1;
            if (string.IsNullOrEmpty(e.path)) e.path = e.name;
        }

        string Header() =>
@"// <auto-generated>
// This file is generated by Tools/Wwise/Generate Event ID Map.
// DO NOT EDIT MANUALLY.
// </auto-generated>

namespace Audio.Generated
{
    /// <summary>
    /// Name → shortId constants for Wwise Events.
    /// Regenerate via Tools/Wwise/Generate Event ID Map after Wwise changes.
    /// </summary>
    public static class AudioEventIDs
    {
";

        string Footer() => @"
    }
}
";

        var sb = new StringBuilder(32 * 1024);
        sb.Append(Header());

        // Emit only constants (no dictionaries)
        foreach (var e in events)
        {
            var ident = ToIdentifier(e.name);
            if (nameCounts[e.name] > 1) ident = $"{ident}_{e.shortId}"; // disambiguate duplicates
            ident = MakeUnique(ident, usedIdentifiers);
            ident = ident.Substring(4); // Remove "EVT_"

            sb.Append("        public const uint ");
            sb.Append(ident);
            sb.Append(" = ");
            sb.Append(e.shortId);
            sb.Append("u; // ");
            sb.AppendLine(e.path);
        }

        sb.Append(Footer());
        return sb.ToString();
    }

    private static string ToIdentifier(string name)
    {
        var s = Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
        if (string.IsNullOrEmpty(s)) s = "_";
        if (char.IsDigit(s[0])) s = "_" + s;
        return s;
    }

    private static string MakeUnique(string ident, HashSet<string> used)
    {
        var baseId = ident;
        var i = 1;
        while (!used.Add(ident))
            ident = baseId + "_" + i++;
        return ident;
    }
}
#endif
